services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - ./n8n/workflows:/home/node/workflows
      - ./data:/home/node/data
      - ./local-files:/home/node/local-files
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=username
      - N8N_BASIC_AUTH_PASSWORD=password
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=postgres
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=bi_projekat
    networks:
      - bi_projekat
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: bi_projekat
    volumes:
      - db_data:/var/lib/postgresql
      - ./data:/data
      - ./local-files:/docker-entrypoint-initdb.d
    networks:
      - bi_projekat

  adminer:
    image: adminer
    restart: always
    ports:
      - 8765:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_PORT: 5432
      ADMINER_DEFAULT_DB: postgres
      ADMINER_DEFAULT_USER: postgres
      ADMINER_DEFAULT_PASSWORD: bi_projekat
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - bi_projekat

volumes:
  n8n_data:
  db_data:


networks:
  bi_projekat:
    driver: bridge
