services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - ./n8n/workflows:/home/node/workflows
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=username
      - N8N_BASIC_AUTH_PASSWORD=password

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: bi_projekat
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - bi_projekat

  adminer:
    image: adminer
    restart: always
    ports:
      - 8765:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_PORT: 5432
      ADMINER_DEFAULT_DB: postgres
      ADMINER_DEFAULT_USER: postgres
      ADMINER_DEFAULT_PASSWORD: bi_projekat
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - bi_projekat

volumes:
  n8n_data:
  db_data:


networks:
  bi_projekat:
    driver: bridge
