services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - TZ="Europe/Sarajevo"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    networks:
      - bi_projekat

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: bi_projekat
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - bi_projekat

  adminer:
    image: adminer
    restart: always
    ports:
      - 8765:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_PORT: 5432
      ADMINER_DEFAULT_DB: postgres
      ADMINER_DEFAULT_USER: postgres
      ADMINER_DEFAULT_PASSWORD: bi_projekat
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - bi_projekat

volumes:
  n8n_data:
  db_data:

networks:
  bi_projekat:
    driver: bridge
