services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - ./n8n/workflows:/home/node/workflows
      - ./data:/home/node/data
      - ./local-files:/home/node/local-files
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_HOST=https://unsocialised-sweetless-journee.ngrok-free.dev/
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - WEBHOOK_URL=https://unsocialised-sweetless-journee.ngrok-free.dev/
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_INSTALL_PACKAGES=n8n-nodes-discord-trigger
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - DB_POSTGRESDB_HOST=${POSTGRES_HOST}
      - DB_POSTGRESDB_PORT=${POSTGRES_PORT}
      - DB_POSTGRESDB_DATABASE=postgres
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - bi_projekat
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql
      - ./data:/data
      - ./local-files:/docker-entrypoint-initdb.d
    networks:
      - bi_projekat

  adminer:
    image: adminer
    restart: always
    ports:
      - 8765:8080
    environment:
      ADMINER_DEFAULT_SERVER: ${POSTGRES_HOST}
      ADMINER_DEFAULT_PORT: ${POSTGRES_PORT}
      ADMINER_DEFAULT_DB: postgres
      ADMINER_DEFAULT_USER: ${POSTGRES_USER}
      ADMINER_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - bi_projekat

volumes:
  n8n_data:
  db_data:


networks:
  bi_projekat:
    driver: bridge
